[package]
name = "cargo-rdme"
description = "Cargo command to create your `README.md` from your crate's documentation"
version = "2.2.4-pre"
authors = ["Diogo Sousa <diogogsousa@gmail.com>"]

edition = "2024"
rust-version = "1.96.0"

homepage = "https://github.com/orium/cargo-rdme"
repository = "https://github.com/orium/cargo-rdme"
documentation = "https://docs.rs/cargo-rdme"
readme = "README.md"

keywords = ["readme", "cargo", "documentation"]
categories = ["development-tools::cargo-plugins"]

license = "MIT"

# What to include when packaging.
include = [
    "/src/**/*.rs",
    "/Cargo.toml",
    "/Cargo.lock",
    "/LICENSE.md",
    "/README.md",
    "/release-notes.md",
]

[badges]
codecov = { repository = "orium/cargo-rdme", branch = "main", service = "github" }

[dependencies]
cargo_metadata = "0.23.1"
clap = "4.6.7"
clap-cargo = "0.19.0"
dunce = "1.0.5"
gix = { version = "0.87.1", default-features = false, features = ["status", "dirwalk", "sha1"] }
indoc = "2.0.7"
itertools = "0.15.0"
pulldown-cmark = "0.13.4"
rustdoc-json = "0.9.10"
rustdoc-types = "0.61.0"
rustup-toolchain = "0.1.10"
serde_json = "1.0.151"
syn = { version = "3.0.6", features = ["full", "extra-traits"] }
termcolor = "1.4.1"
thiserror = "2.0.20"
toml = "1.1.6"
unicase = "2.9.0"

[dev-dependencies]
pretty_assertions = "1.4.1"

[lints.clippy]
all = { level = "warn", priority = -2 }
correctness = { level = "deny", priority = -1 }
pedantic = { level = "warn", priority = -2 }

enum_variant_names = "allow"
if_not_else = "allow"
inline_always = "allow"
match_bool = "allow"
match_same_arms = "allow"
missing_errors_doc = "allow"
module_name_repetitions = "allow"
needless_raw_string_hashes = "allow"
new_without_default = "allow"
non_ascii_literal = "allow"
partialeq_ne_impl = "allow"
similar_names = "allow"
single_match_else = "allow"
struct_excessive_bools = "allow"
use_self = "allow"
